feign:
  circuitbreaker:
    enabled: true
book-service-client1:
  name: book-service1
  domain-url: http://localhost:5500
  username: test
  password: password
  retrieve-book:
    url: /book/{id}

book-service-client2:
  name: book-service2
  domain-url: http://localhost:4000
  username: user
  password: pass
  retrieve-book:
    url: /book/{id}
